application: sojourn-audio
version: master
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: "/resource"
  static_dir: resource
  secure: always
  expiration: 4d
- url: "/admin/.*"
  script: sojourn._app.APP
  secure: always
  login: admin
- url: "/railz-resource"
  static_dir: lib/railz/resource
  secure: always
  expiration: 4d
- url: "/.*"
  script: sojourn._app.APP
  secure: always

libraries:
- name: lxml
  version: latest
- name: jinja2
  version: latest
- name: yaml
  version: latest
- name: pycrypto
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- node_modules/(.*)
- datastore