#!/usr/bin/python
import os
import sys

submodule = sys.argv[1]
msg = sys.argv[2]

os.system("""git --git-dir=%s/.git add -A""" % submodule)
os.system("""git --git-dir=%s/.git commit -m "%s" """ % (submodule, msg))
os.system("""git --git-dir=%s/.git rebase HEAD master""" % submodule)
os.system("""git --git-dir=%s/.git push origin master""" % submodule)

print "You still need to commit the base repo to point to the updated master."